# This is a basic workflow to help you get started with Actions

name: githubTweeter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tweet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # add python to run python file
      - uses: actions/checkout@v2
      
      - name: get python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      
      - name: grab push data
        run: |
          AUTHOR=${{ github.event.comment.user.login }}
          DATE=${{ github.event.comment.created_at }}
          COMMENT=$(echo "${{ github.event.comment.body }}")

    
      #- name: run python script
       # run: |
        #  python main.py AUTHOR DATE COMMENT
      
      - name: store test artifacts
        run: |
          echo ${COMMENT} > ./artifactsTest.txt
          
      - uses: actions/upload-artifact@v2
        with:
          name: artifactsTest
          path: ./
