# This is a basic workflow to help you get started with Actions

name: githubTweeter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tweet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # add python to run python file
      - uses: actions/checkout@v2
      
      - name: get python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
          
      - name: install urllib3
        run: pip install urllib3
      
      - name: grab push data
        run: |
          echo ${{github.event.commits[0].message}} > artifactsTest.txt    
          COMMITS_SIZE=${#COMMITS[@]}
          
      - name: run main.py
        run: |
          for ((i=0;i<=COMMITS_SIZE;i++))
          do 
          echo "$i"
          COMMITS="$(jq '.commits' $GITHUB_EVENT_PATH)"
          #echo "test"
          MSG="$(jq '.message' $COMMITS[$i])"
          echo $MSG
          MSG="$(jq '.commit.message' $COMMITS[$i])"
          echo $MSG
          python main.py $MSG
          done
          
          
      
      - name: store test artifacts          
        uses: actions/upload-artifact@v2
        with:
          name: artifactsTest
          path: ./artifactsTest.txt
